# Generated by Django 4.0 on 2021-12-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_date', models.DateTimeField()),
                ('date', models.DateTimeField()),
                ('category', models.CharField(default='', max_length=20)),
                ('subCategory', models.CharField(default='', max_length=20)),
                ('item', models.TextField(default='')),
                ('originalCurrency', models.CharField(default='', max_length=5)),
                ('newCurrency', models.CharField(max_length=5, null=True)),
                ('originalAmount', models.FloatField(null=True)),
                ('newAmount', models.FloatField(null=True)),
                ('comment', models.TextField(default='')),
                ('expense_income', models.CharField(max_length=10)),
            ],
        ),
    ]
